const steps=["開始","キーボード","スピーカー","カメラ","マイク","液晶＋タッチ","タッチパッド / Wi-Fi","完了"];
let idx=0,results={},cameraStream=null,micStream=null,audioCtxForMic=null,cameraDevices=[],cameraIndex=0;
function updateFrame(){document.getElementById("stepText").textContent=`Step ${Math.min(idx,steps.length-1)}/${steps.length-1}`;document.getElementById("stepName").textContent=steps[idx];document.getElementById("bar").style.width=`${(idx/(steps.length-1))*100}%`;document.getElementById("statusPill").textContent=idx===0?"待機":steps[idx];}
function render(){stopMedia();updateFrame();const c=document.getElementById("content");
if(idx===0){c.innerHTML=`<div class="center"><div class="big">Chromebook Check</div><p class="sub">端末情報を確認してから検査を開始します。</p></div><div class="spec-grid"><div class="spec-card"><div class="label">ChromeOS / ブラウザ</div><div class="value" id="specChrome">取得中...</div></div><div class="spec-card"><div class="label">画面解像度</div><div class="value" id="specResolution">取得中...</div></div><div class="spec-card"><div class="label">バッテリー</div><div class="value" id="specBattery">取得中...</div></div><div class="spec-card"><div class="label">充電状態</div><div class="value" id="specCharging">取得中...</div></div><div class="spec-card"><div class="label">ネットワーク</div><div class="value" id="specOnline">取得中...</div></div><div class="spec-card"><div class="label">ストレージ推定</div><div class="value">chrome://system解析推奨</div></div></div><details class="parser-box"><summary>chrome://system からCPU/メモリ/ストレージを解析する</summary><div class="note">1. 別タブで <strong>chrome://system</strong> を開く<br>2. cpuinfo / meminfo / storage_info を Expand<br>3. Ctrl+A → Ctrl+C<br>4. 下の欄へ貼り付け</div><textarea id="systemPaste" placeholder="chrome://system の内容をここに貼り付け"></textarea><button class="btn start" onclick="parseSystemInfo()">解析する</button><div class="spec-grid"><div class="spec-card"><div class="label">CPU解析</div><div class="value" id="parsedCpu">未解析</div></div><div class="spec-card"><div class="label">メモリ解析</div><div class="value" id="parsedMem">未解析</div></div><div class="spec-card"><div class="label">ストレージ解析</div><div class="value" id="parsedStorage">未解析</div></div></div></details><div class="actions"><button class="btn start" onclick="next()">▶ 検査開始</button></div>`;collectSpecs();return;}
if(idx===1){c.innerHTML=`<h2>キーボード</h2><div class="sub">まずChromeOS標準診断を試します。開けない場合は簡易キーボード検査を使います。</div><div class="note"><strong>標準診断</strong><br>アドレスバーに <strong>chrome://diagnostics</strong> を入力して、キーボードテストを実施してください。<br>Webページから直接開けない機種があります。</div><div class="diagnostic-url" onclick="copyDiagnosticsUrl()">chrome://diagnostics</div><div class="actions"><button class="btn start" onclick="openDiagnostics()">▶ 標準診断を試す</button><button class="btn start" onclick="showSimpleKeyboard()">▶ 簡易キーボード検査</button></div><div id="simpleKeyboardArea"></div><div class="actions"><button class="btn ng" onclick="fail('キーボード')">❌ NG</button><button class="btn ok" onclick="passStep('キーボード')">✅ OK</button></div>`;return;}
if(idx===2){c.innerHTML=`<h2>スピーカー</h2><div class="sub">左「ド・ソ・シ」→右「ド・ソ・シ」を短く自動再生します。</div><div class="speaker-box"><div class="speaker" id="leftSpeaker"><h2>左</h2><div class="tone" id="leftTone">待機</div></div><div class="speaker" id="rightSpeaker"><h2>右</h2><div class="tone" id="rightTone">待機</div></div></div><div class="center"><button class="btn start" onclick="playSpeakerTest()">▶ テスト開始</button></div><div class="actions"><button class="btn ng" onclick="fail('スピーカー')">❌ NG</button><button class="btn ok" onclick="passStep('スピーカー')">✅ OK</button></div>`;return;}
if(idx===3){c.innerHTML=`<h2>カメラ</h2><div class="sub">カメラ映像を確認します。複数カメラがある場合は切り替えて確認してください。</div><div class="actions"><button class="btn start" onclick="startCamera()">▶ カメラ起動</button><button class="btn start" onclick="switchCamera()">🔁 カメラ切替</button></div><div class="note" id="cameraInfo">カメラ未起動</div><video id="cameraPreview" class="preview" autoplay playsinline muted></video><div class="actions"><button class="btn ng" onclick="fail('カメラ')">❌ NG</button><button class="btn ok" onclick="passStep('カメラ')">✅ OK</button></div>`;return;}
if(idx===4){c.innerHTML=`<h2>マイク</h2><div class="sub">声を出して、メーターが反応するか確認します。</div><button class="btn start" onclick="startMic()">▶ マイク起動</button><div class="meter"><div class="meter-bar" id="micBar"></div></div><div class="actions"><button class="btn ng" onclick="fail('マイク')">❌ NG</button><button class="btn ok" onclick="passStep('マイク')">✅ OK</button></div>`;return;}
if(idx===5){c.innerHTML=`<h2>液晶＋タッチパネル</h2><div class="sub">全画面で色確認を行い、そのまま5か所タッチ検査に進みます。</div><div class="center"><button class="btn start" onclick="startLcdTouchFullscreen()">▶ 全画面で開始</button></div><div class="actions"><button class="btn ng" onclick="fail('液晶＋タッチパネル')">❌ NG</button><button class="btn ok" onclick="passStep('液晶＋タッチパネル')">✅ OK</button></div>`;return;}
if(idx===6){c.innerHTML=`<h2>タッチパッド / Wi-Fi</h2><div class="sub">カーソルを丸まで動かし、Wi-Fi接続状態も確認します。</div><div class="note">Wi-Fi状態: <strong>${navigator.onLine?"接続中":"未接続"}</strong></div><div class="target-area" onmousemove="checkPointer(event)"><div class="target" id="target">○</div></div><div class="actions"><button class="btn ng" onclick="fail('タッチパッド / Wi-Fi')">❌ NG</button><button class="btn ok" onclick="passStep('タッチパッド / Wi-Fi')">✅ OK</button></div>`;return;}
if(idx===7){const items=Object.entries(results).map(([k,v])=>`<div class="spec-card"><div class="label">${k}</div><div class="value ${v==='OK'?'pass':'fail'}">${v}</div></div>`).join("");c.innerHTML=`<div class="center"><div class="big pass">🎉 PASS</div><p class="sub">検査完了</p></div><div class="spec-grid">${items}</div><div class="actions"><button class="btn start" onclick="location.reload()">次の端末</button></div>`;}}
function next(){idx++;render()}function passStep(n){results[n]="OK";next()}function fail(n){stopMedia();results[n]="NG";document.getElementById("bar").style.width="100%";document.getElementById("statusPill").textContent="FAIL";document.getElementById("content").innerHTML=`<div class="center"><div class="big fail">❌ FAIL</div><p class="sub">${n} でNG判定</p><button class="btn start" onclick="location.reload()">次の端末</button></div>`}
async function collectSpecs(){const ua=navigator.userAgent||"",m=ua.match(/CrOS\s+([^\s]+)\s+([0-9.]+)/);document.getElementById("specChrome").textContent=m?`ChromeOS ${m[2]}`:"取得不可";document.getElementById("specResolution").textContent=`${screen.width} × ${screen.height} / DPR ${window.devicePixelRatio||1}`;document.getElementById("specOnline").textContent=navigator.onLine?"接続中":"未接続";if("getBattery"in navigator){try{const b=await navigator.getBattery();document.getElementById("specBattery").textContent=`${Math.round(b.level*100)}%`;document.getElementById("specCharging").textContent=b.charging?"充電中":"未充電"}catch(e){document.getElementById("specBattery").textContent="取得不可";document.getElementById("specCharging").textContent="取得不可"}}else{document.getElementById("specBattery").textContent="非対応";document.getElementById("specCharging").textContent="非対応"}}
function parseSystemInfo(){const text=document.getElementById("systemPaste")?.value||"";const cm=text.match(/model name\s*:\s*(.+)/i);let cpu=cm?cm[1].trim():"未検出";cpu=cpu.replace(/Intel\(R\)|CPU|@.+$/g,"").replace(/Celeron\(R\)/g,"Celeron").replace(/\s+/g," ").trim();document.getElementById("parsedCpu").textContent=cpu||"未検出";const mm=text.match(/MemTotal:\s*([0-9]+)\s*kB/i);let mem="未検出";if(mm){const gb=Number(mm[1])/1024/1024;if(gb<3)mem="2GB";else if(gb<6)mem="4GB";else if(gb<12)mem="8GB";else if(gb<24)mem="16GB";else mem=Math.round(gb)+"GB"}document.getElementById("parsedMem").textContent=mem;let storage="未検出";const sec=text.match(/(?:SEC_COUNT|sector count|sectors|rel_sectors)\s*[:|]\s*([0-9]+)/i);if(sec){storage=normalizeStorageGb(Number(sec[1])*512/(1000**3))}else{const nm=text.match(/name\s*\|\s*([A-Za-z0-9_-]+)/i)||text.match(/name\s*[:]\s*([A-Za-z0-9_-]+)/i);if(nm)storage="型番: "+nm[1].trim()}document.getElementById("parsedStorage").textContent=storage}
function normalizeStorageGb(gb){if(gb<24)return"16GB";if(gb<48)return"32GB";if(gb<96)return"64GB";if(gb<192)return"128GB";if(gb<384)return"256GB";return Math.round(gb)+"GB"}
function openDiagnostics(){try{window.open("chrome://diagnostics","_blank")}catch(e){}alert("開けない場合は、アドレスバーに chrome://diagnostics と入力してください")}async function copyDiagnosticsUrl(){try{await navigator.clipboard.writeText("chrome://diagnostics");alert("chrome://diagnostics をコピーしました")}catch(e){alert("アドレスバーに chrome://diagnostics と入力してください")}}
const simpleKeyboardRows=["Q W E R T Y U I O P".split(" "),"A S D F G H J K L".split(" "),"Z X C V B N M".split(" "),["Space","Enter","Backspace","ArrowLeft","ArrowRight","ArrowUp","ArrowDown"]];
function showSimpleKeyboard(){const area=document.getElementById("simpleKeyboardArea");area.innerHTML=`<div class="note">簡易検査：表示されたキーを押すと緑になります。全部緑になったらOKを押してください。</div><div class="simple-kb" id="simpleKb"></div>`;const kb=document.getElementById("simpleKb");simpleKeyboardRows.forEach(row=>{const r=document.createElement("div");r.className="simple-kb-row";row.forEach(k=>{const d=document.createElement("div");d.className="simple-key";d.id="simple-"+k;d.textContent=k.replace("ArrowLeft","←").replace("ArrowRight","→").replace("ArrowUp","↑").replace("ArrowDown","↓");r.appendChild(d)});kb.appendChild(r)})}
document.addEventListener("keydown",e=>{if(idx!==1)return;let k=e.key.length===1?e.key.toUpperCase():e.key;if(e.code==="Space")k="Space";if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","Enter","Backspace","Space"].includes(k)||/^[A-Z]$/.test(k)){const el=document.getElementById("simple-"+k);if(el){el.classList.add("done");e.preventDefault()}}});
function wait(ms){return new Promise(r=>setTimeout(r,ms))}async function playTone(freq,pan,label,side){const AC=window.AudioContext||window.webkitAudioContext,ctx=new AC(),osc=ctx.createOscillator(),gain=ctx.createGain(),p=ctx.createStereoPanner?ctx.createStereoPanner():null;osc.frequency.value=freq;osc.type="sine";gain.gain.value=.40;if(p){p.pan.value=pan;osc.connect(gain).connect(p).connect(ctx.destination)}else osc.connect(gain).connect(ctx.destination);document.getElementById(side+"Tone").textContent=label;document.getElementById(side+"Speaker").classList.add("active");osc.start();await wait(280);osc.stop();ctx.close();document.getElementById(side+"Speaker").classList.remove("active")}
async function playSpeakerTest(){document.getElementById("leftTone").textContent="待機";document.getElementById("rightTone").textContent="待機";const notes=[[261.63,"ド"],[392,"ソ"],[493.88,"シ"]];for(const [f,l]of notes){await playTone(f,-1,l,"left");await wait(80)}document.getElementById("leftTone").textContent="完了";await wait(150);for(const [f,l]of notes){await playTone(f,1,l,"right");await wait(80)}document.getElementById("rightTone").textContent="完了"}
async function refreshCameraDevices(){try{const d=await navigator.mediaDevices.enumerateDevices();cameraDevices=d.filter(x=>x.kind==="videoinput")}catch(e){cameraDevices=[]}}async function startCamera(deviceId=null){try{stopMedia();await refreshCameraDevices();const constraints={video:deviceId?{deviceId:{exact:deviceId}}:true,audio:false};cameraStream=await navigator.mediaDevices.getUserMedia(constraints);const v=document.getElementById("cameraPreview");v.srcObject=cameraStream;v.style.display="block";await refreshCameraDevices();const info=document.getElementById("cameraInfo"),label=cameraDevices[cameraIndex]?.label||`カメラ ${cameraIndex+1}`;if(info)info.textContent=`使用中: ${label} / 検出数: ${cameraDevices.length||"不明"}`}catch(e){alert("カメラを起動できません: "+e.message)}}async function switchCamera(){await refreshCameraDevices();if(cameraDevices.length<=1){alert("切替可能なカメラが見つかりません");return}cameraIndex=(cameraIndex+1)%cameraDevices.length;await startCamera(cameraDevices[cameraIndex].deviceId)}
async function startMic(){try{micStream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});const AC=window.AudioContext||window.webkitAudioContext;audioCtxForMic=new AC();const source=audioCtxForMic.createMediaStreamSource(micStream),analyser=audioCtxForMic.createAnalyser();source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);function loop(){if(idx!==4)return;analyser.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/data.length,bar=document.getElementById("micBar");if(bar)bar.style.width=Math.min(100,avg*2)+"%";requestAnimationFrame(loop)}loop()}catch(e){alert("マイクを起動できません: "+e.message)}}function stopMedia(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}if(audioCtxForMic){audioCtxForMic.close();audioCtxForMic=null}}
async function requestFullScreen(el){try{if(el.requestFullscreen)await el.requestFullscreen();else if(el.webkitRequestFullscreen)await el.webkitRequestFullscreen()}catch(e){}}async function exitFullScreen(){try{if(document.fullscreenElement&&document.exitFullscreen)await document.exitFullscreen();else if(document.webkitFullscreenElement&&document.webkitExitFullscreen)await document.webkitExitFullscreen()}catch(e){}}
let lcdTouchMode="color",lcdTouchIndex=0,touchedPoints=new Set();const lcdTouchColors=[["WHITE","white","black"],["BLACK","black","white"],["RED","red","white"],["GREEN","lime","black"],["BLUE","blue","white"]];
function startLcdTouchFullscreen(){let box=document.getElementById("lcdTouchFullscreen");if(!box){box=document.createElement("div");box.id="lcdTouchFullscreen";box.className="lcd-fullscreen";box.innerHTML=`<div class="fullscreen-top"><div class="fullscreen-title" id="lcdTouchTitle">液晶色テスト</div><button class="btn fullscreen-exit" onclick="closeLcdTouchFullscreen(event)">閉じる</button></div><div id="lcdTouchBody" class="lcd-color-name">WHITE</div>`;document.body.appendChild(box);box.addEventListener("click",advanceLcdTouch)}lcdTouchMode="color";lcdTouchIndex=0;touchedPoints=new Set();box.classList.add("show");renderLcdTouch();requestFullScreen(box)}
function renderLcdTouch(){const box=document.getElementById("lcdTouchFullscreen"),body=document.getElementById("lcdTouchBody"),title=document.getElementById("lcdTouchTitle");if(lcdTouchMode==="color"){const [name,bg,fg]=lcdTouchColors[lcdTouchIndex];box.style.background=bg;box.style.color=fg;title.textContent="液晶色テスト";body.className="lcd-color-name";body.textContent=name}else{box.style.background="#020617";box.style.color="white";title.textContent="タッチパネル検査：5か所タッチ";body.className="fullscreen-touch-area";body.innerHTML=`<div class="fullscreen-touch-dot" data-touch="tl">左上</div><div class="fullscreen-touch-dot" data-touch="tr">右上</div><div class="fullscreen-touch-dot" data-touch="c">中央</div><div class="fullscreen-touch-dot" data-touch="bl">左下</div><div class="fullscreen-touch-dot" data-touch="br">右下</div>`;body.querySelectorAll("[data-touch]").forEach(dot=>{dot.onpointerdown=e=>markTouchPoint(e,dot);dot.ontouchstart=e=>markTouchPoint(e,dot)})}}
function advanceLcdTouch(e){if(e&&e.target&&(e.target.classList.contains("fullscreen-exit")||e.target.dataset.touch))return;if(lcdTouchMode!=="color")return;lcdTouchIndex++;if(lcdTouchIndex>=lcdTouchColors.length)lcdTouchMode="touch";renderLcdTouch()}
function markTouchPoint(e,dot){e.preventDefault();dot.classList.add("hit");touchedPoints.add(dot.dataset.touch);if(touchedPoints.size===5&&idx===5){results["液晶＋タッチパネル"]="OK";setTimeout(()=>{closeLcdTouchFullscreen();next()},500)}}function closeLcdTouchFullscreen(e){if(e)e.stopPropagation();document.getElementById("lcdTouchFullscreen")?.classList.remove("show");exitFullScreen()}
function checkPointer(e){const target=document.getElementById("target");if(!target)return;const r=target.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){target.classList.add("hit");target.textContent="OK"}}
render();
